### ISSUE TITLE
Tab spacing is not working for Python

### ISSUE THREAD

**Issue by prithvirajkadiyala** [kipr/harrogate#83]

**Comment by prithvirajkadiyala** [comment]
https://github.com/kipr/harrogate/blob/d5e55e0b78755ce4ecc70bc8738854f3e6b5dc9d/apps/kiss/resources/kiss-view-controller.js#L418

Here is where the code for indentation is.

**Comment by prithvirajkadiyala** [comment]
https://github.com/kipr/harrogate/blob/cfdb10835f195aeb64904b27131b6e8afdc1a564/apps/kiss/resources/kiss-view-controller.js#L29

Further investigation led me to this.

**Comment by prithvirajkadiyala** [comment]
Seems like CodeMirror hasn't figured out the issue with Python indentation and spacing yet.

https://github.com/codemirror/CodeMirror/issues/4119

**Comment by Zacharyprime** [comment]
I tried messing around with this file:
https://github.com/kipr/harrogate/blob/cfdb10835f195aeb64904b27131b6e8afdc1a564/apps/kiss/resources/kiss-view-controller.js

```sh
 editor = code_mirror.fromTextArea(document.getElementById('editor'), {
    mode: 'text/x-csrc',
    lineNumbers: true,
    indentUnit: 4,
    theme: 'kiss',
    viewportMargin: Infinity
  });
```

I tried to change the indexUnit to something else, that didn't effect anything.
I also tried changing the indent mode, but now looking at this I can't remember if I edited the mode: shown above or if the parameter was called "indentMode". I was reading from the codemirror docs to make the change.

If I did do the mode correctly, changing to spacing mode instead of tab mode did not even take effect.

I might take another shot at this since I can't remember how I did the mode change.

**Comment by Zacharyprime** [comment]
https://codemirror.net/doc/manual.html

I did not change "mode:" I added something like "indentMode" but since it's not in the docs I must have found that in a forum. I bet that the forum person was just wrong.

**Comment by Zacharyprime** [comment]
https://github.com/kipr/harrogate/pull/108

```js
 mode: 'text/x-csrc',
    lineNumbers: true,
    indentUnit: 4,
    smartIndent: false,
    theme: 'kiss',
    viewportMargin: Infinity
  });
```

**Comment by Zacharyprime** [comment]
(The automation was setup wrong, that was me testing it)
