### ISSUE TITLE
Randomly returns to Desktop screen when about button is clicked

### ISSUE THREAD

**Issue by tcorbly** [kipr/harrogate#90]
This seems to happen more frequently when an ethernet cable is plugged. The UI closes and has to be restarted by clicking the Botguy icon on the screen.

**Comment by Zacharyprime** [comment]
It's worth noting that the about page version doesn't actually mean anything since we haven't been bumping it when we make changes.

I would suggest removing it or we can make it match the overall OS version (26.0 as of writing this)

Braden is also working on Ivygate which is expected to replace harrogate if that is still his plan

**Comment by Zacharyprime** [comment]
I have not been able to recreate this with no luck.

I tried both with and without the ethernet cable (not sure why that would be relevant anyway)

I have been tabbing back and forth and restarting this Wombat for a while now, so it's either a very specific scenario or it doesn't happen anymore.

It's also possible you got the bad version from when I let dependabot bump jquery and angular and it broke some things.

This also made me take a fresh look at harrogate and reminded me how due we are for a new harrogate. Hopefully we can use Ivygate soon.

**Comment by Zacharyprime** [comment]
I think that this is actually an issue with botui and not harrogate. I have had the about page crash with botui a few times since I last looked at this issue, but it's almost always because something was setup incorrectly and you just need to update the controller.
